# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Landon Lehman
tagline:          'physics!'
description:      'physics!'
url:              http://landonlehman.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:
 - jekyll-paginate
 - jekyll-gist

# Google services
google_analytics: UA-82442631-1
